### ISSUE TITLE
Path issue. (NOT A BUG)

### ISSUE THREAD

**Issue by AsynchronousAI** [mingodad/ljs-5.4#1]
This is a small thing I wanted to point out, I think you changed the path for personal use to 
```c
#define LUA_ROOT	"/home/mingo/local/ljs-5.4.4/"
```
when it should be
```c
#define LUA_ROOT	"/usr/local/"
```
which you did comment out, Idk if you forgot to change it back. If you would like I can make a PR of a fix.

**Comment by mingodad** [comment]
Thanks for pointing it out !
In reality it should be a user defined path:
```
#ifndef LUA_ROOT
#define LUA_ROOT	"/usr/local/"
#endif
```
